version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    env_file:
      - ./.env
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - greenhouse-network

  greenhouse-service:
    build: .
    image: teodor2002/greenhouse-service
    container_name: greenhouse-service
    env_file:
      - ./.env
    depends_on:
      - mariadb
    ports:
      - "8088:8088"
    restart: unless-stopped
    networks:
      - greenhouse-network

networks:
  greenhouse-network:
    external: true

volumes:
  mariadb-data: