version: "3.9"

services:
  green-loader:
    build: .
    image: teodor2002/green-loader
    container_name: green-loader
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    restart: unless-stopped